exchangerate:
  api-key: API_KEY
rapid:
  api-key: API_KEY
spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://localhost:5432/consumer
    username: postgres
    password: postgres
  jpa:
    defer-datasource-initialization: true
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  mvc:
    cors:
      allowed-origins: "*"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  sql:
    init:
      mode: always
jwt:
  secret-key: API_KEY




